export const SET_USER = "SET_USER"
export const LOGIN = "LOGIN"
export const SIGNUP = "SIGNUP"
export const AUTHENTICATED = "AUTHENTICATED"
export const SET_INGREDIENTS = "SET_INGREDIENTS"
export const SIGNOUT = "SIGNOUT"